# Generated by Django 3.2.4 on 2023-11-29 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_encuesta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
