# Generated by Django 3.2.4 on 2023-12-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inflable',
            fields=[
                ('idInfla', models.AutoField(db_column='idInflable', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', default='Nombre', max_length=100)),
                ('Ancho', models.IntegerField(db_column='Ancho', default='0')),
                ('Largo', models.IntegerField(db_column='Largo', default='0')),
                ('Alto', models.IntegerField(db_column='Alto', default='0')),
            ],
            options={
                'db_table': 'Inflable',
            },
        ),
        migrations.CreateModel(
            name='Toro',
            fields=[
                ('idToro', models.AutoField(db_column='idToro', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', default='Nombre', max_length=100)),
                ('Ancho', models.IntegerField(db_column='Ancho', default='0')),
                ('Largo', models.IntegerField(db_column='Largo', default='0')),
                ('Alto', models.IntegerField(db_column='Alto', default='0')),
            ],
            options={
                'db_table': 'Toro',
            },
        ),
        migrations.CreateModel(
            name='Trampolin',
            fields=[
                ('idTramp', models.AutoField(db_column='idTramp', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', default='Nombre', max_length=100)),
                ('Ancho', models.IntegerField(db_column='Ancho', default='0')),
                ('Largo', models.IntegerField(db_column='Largo', default='0')),
                ('Alto', models.IntegerField(db_column='Alto', default='0')),
                ('Resorte', models.IntegerField(db_column='Resorte', default='0')),
            ],
            options={
                'db_table': 'Trampolin',
            },
        ),
        migrations.RemoveField(
            model_name='favoritos',
            name='fk_Libro',
        ),
        migrations.RemoveField(
            model_name='favoritos',
            name='fk_Usuario',
        ),
        migrations.RemoveField(
            model_name='resenas',
            name='fk_Libro',
        ),
        migrations.RemoveField(
            model_name='resenas',
            name='fk_Usuario',
        ),
        migrations.DeleteModel(
            name='Biblioteca_Personal',
        ),
        migrations.DeleteModel(
            name='Favoritos',
        ),
        migrations.DeleteModel(
            name='Libros',
        ),
        migrations.DeleteModel(
            name='Resenas',
        ),
    ]
